version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  dependency_file_paths = [ 
    "packages/cli/package.json", 
    "packages/core/package.json",
    "packages/node-dev/package.json",
    "packages/nodes-base/package.json",
    "packages/workflow/package.json",
    "packages/editor-ui/package.json"
  ]
  plugins = ['vue']
